### ISSUE TITLE
Questions about the fork

### ISSUE THREAD

**Issue by jnoxon** [asantoni/marlin-monoprice-select-mini#1]
Does this work with the MCU in the MP Select Mini, or is this something you're using with a RAMPS board grafted into the MP printer? I was under the impression this printer was running a heavily modified Marlin firmware already; If it can run stock Marlin that would be amazing. Thanks!

**Comment by asantoni** [comment]
This is for a RAMPS board grafted into an MP Select Mini. I've talked to
people who are trying to get Marlin working on the stock Mini board but I'm
not sure of the status of that effort. I think there's a Marlin bug thread
about it. I'll try to dig it up tomorrow if I remember.

Thanks for your interest!

**Comment by EpicSalvation** [comment]
Any word on this?

**Comment by asantoni** [comment]
Nothing new from me, but Marlin 2.0 has a config built-in for the Malyan M200, which is the Monoprice Select Mini:
https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x/config/examples/Malyan/M200

I'd recommend trying to build with that config and see if you can find some documentation. It's unclear to me if Marlin 2.0 runs directly on the original MCU or if it's meant for a RAMPS replacement. (My hunch is that it runs on the original MCU, so you might be in luck.)
